### ISSUE TITLE
Perhaps can refactor to this.

### ISSUE THREAD

**Issue by SanCoder-Q** [abruzzi/mommifier#1]
```
function mommify(inputStr){
  return (inputStr.match(/[aeiou]/gmi)||[]).length * 10 > 3 * inputStr.length ? inputStr.replace(/[aeiou]+/gmi,"mommy") : inputStr ;
}
```

One-line but less readability, how to balance?

**Comment by abruzzi** [comment]
I would prefer readability first, the code is for human to maintain anyway. And it's very important to understand that usually you are working with a whole team, not just yourself, right? So help others to understand your purpose is as important as the code works.

**Comment by SanCoder-Q** [comment]
I think you are right. The dev-speed of a whole team is much important than a individual code style.
